# Optional shortcuts. The stack itself needs only:  docker compose up --watch
SHELL := /bin/bash
COMPOSE := docker compose
DEV := $(COMPOSE)
PROD := $(COMPOSE) --profile prod
STAMP := $(shell date +%Y%m%d-%H%M%S)

.DEFAULT_GOAL := help
.PHONY: help dev prod down logs ps psql migrate revision backup restore lint fmt check-content nuke

help: ## Show targets
	@grep -E '^[a-z-]+:.*##' $(MAKEFILE_LIST) | awk -F':.*## ' '{printf "  \033[36m%-10s\033[0m %s\n", $$1, $$2}'

dev: ## Same as: docker compose up --watch
	$(DEV) up --watch

prod: ## Build + run the production images on http://localhost:8088 (detached)
	$(PROD) up --build -d db api proxy

down: ## Stop everything (keeps the database volume)
	$(COMPOSE) --profile prod down

logs: ## Tail logs of running services
	$(COMPOSE) --profile prod logs -f --tail=100

ps: ## List running services
	$(COMPOSE) --profile prod ps

psql: ## Open psql inside the db container
	$(COMPOSE) exec db sh -c 'psql -U "$$POSTGRES_USER" -d "$$POSTGRES_DB"'

migrate: ## Apply migrations (also runs automatically on api start)
	$(DEV) exec api-dev alembic upgrade head

revision: ## New autogenerated migration: make revision m="add thing"
	@test -n "$(m)" || { echo 'usage: make revision m="message"'; exit 1; }
	$(DEV) exec api-dev alembic revision --autogenerate -m "$(m)"

backup: ## Dump the whole database to ./backups/<timestamp>.sql
	@mkdir -p backups
	$(COMPOSE) exec -T db sh -c 'pg_dump -U "$$POSTGRES_USER" -d "$$POSTGRES_DB" --clean --if-exists --no-owner' > backups/workflow-habits-$(STAMP).sql
	@echo "→ backups/workflow-habits-$(STAMP).sql"

restore: ## Restore a dump: make restore f=backups/workflow-habits-XXXX.sql
	@test -f "$(f)" || { echo 'usage: make restore f=backups/<file>.sql'; exit 1; }
	$(COMPOSE) exec -T db sh -c 'psql -v ON_ERROR_STOP=1 -U "$$POSTGRES_USER" -d "$$POSTGRES_DB"' < $(f)

# Ruff runs in a throwaway api-dev container with ./backend mounted, so fixes land in your repo.
RUFF := $(DEV) run --rm --no-deps -T -v ./backend:/app -e RUFF_CACHE_DIR=/tmp/ruff --entrypoint ruff api-dev

# Frontend checks mount ./frontend/src too: `exec` would lint the container's copy, which can be stale.
NODE := $(DEV) run --rm --no-deps -T -v ./frontend/src:/app/src -v ./frontend/scripts:/app/scripts -v ./frontend/eslint.config.js:/app/eslint.config.js web-dev

check-content: ## Enforce copy limits on the brief (docs/content.md)
	$(NODE) node scripts/check-content.ts

lint: ## ESLint + tsc (frontend) and Ruff (backend) on your current files, inside containers
	$(NODE) npx eslint .
	$(NODE) npx tsc --noEmit
	$(NODE) node scripts/check-content.ts
	$(RUFF) check app migrations
	$(RUFF) format --check app migrations

fmt: ## Ruff fix + format the backend (writes to ./backend)
	$(RUFF) check --fix app migrations
	$(RUFF) format app migrations

nuke: ## Stop everything AND delete the database volume
	$(COMPOSE) --profile prod down -v
