import type { Slide } from "./types";

/**
 * The deck. Rule of thumb: a slide carries one idea in a few short lines.
 * Anything longer goes in `details` (opened with "i") or a line's `more`
 * (opened by clicking the line). Each fact appears once.
 */
export const SLIDES: Slide[] = [
  { id: "title", chapter: "intro", kind: "title", transition: "zoom" },

  // ── 01 framing ───────────────────────────────────────────────────────────
  { id: "framing", chapter: "framing", kind: "chapter", transition: "iris" },
  {
    id: "framing-compare",
    chapter: "framing",
    kind: "compare",
    transition: "wipe",
    heading: "Two different objects",
    columns: [
      { title: "Workflow", lines: ["Predefined code paths.", "You own the control flow."], emphasis: true },
      { title: "Agent", lines: ["The model directs its own process.", "It picks its own tools."] },
    ],
    details: [
      "A memory-backed workflow: the human owns the control flow; the model executes steps inside it.",
      "Same source: start with the simplest solution — for many applications a single well-prompted call with retrieval is enough.",
      "Caveat: reviewers note Anthropic's definitions of agentic, workflow and agent are not fully consistent; practitioners treat it as a gradient of autonomy, not two boxes.",
    ],
    sources: [
      { label: "Anthropic — Building effective agents", href: "https://www.anthropic.com/engineering/building-effective-agents" },
      { label: "AgentPatterns map", href: "https://agentpatterns.ai/patterns/agent-design/anthropic-effective-agents-framework/" },
    ],
  },
  {
    id: "framing-axis",
    chapter: "framing",
    kind: "statement",
    transition: "rise",
    heading: "Ask every tool two questions.",
    lines: [
      { text: "Who owns the control flow — you or the model?" },
      { text: "Who owns the memory — readable by you, or extracted and opaque?" },
      { text: "The workflow thesis: the human owns both." },
    ],
    details: ["User agency and transparency become design properties, not afterthoughts."],
  },
  {
    id: "framing-board",
    chapter: "framing",
    kind: "widget",
    widget: "control-memory-board",
    guide: {
      name: "Who's in charge of what",
      shows: "Each lens is an AI tool. Left to right: who decides the next step, you or the model. Top to bottom: whether you can read and edit its memory.",
      try: "Drag a tool to where you think it sits, or add one you use. Positions are saved in this app.",
      point: "Top left is this talk's argument: you steer, and you keep notes you can read. Further right and down, there's less you can check.",
      data: ["yours", "opinion"],
    },
    transition: "push",
  },

  // ── 02 evidence ──────────────────────────────────────────────────────────
  { id: "evidence", chapter: "evidence", kind: "chapter", transition: "iris" },
  {
    id: "evidence-rot",
    chapter: "evidence",
    kind: "stat",
    transition: "zoom",
    study: "Chroma gave 18 AI models simple tasks, then buried the useful part in more and more surrounding text.",
    value: "300 vs 113k",
    label: "tokens: a short, focused prompt beat the same model given the whole history",
    meaning: "Every model got worse as the text grew, even when the answer was sitting in it.",
    source: "Context Rot · Chroma 2025",
    details: ["A token is roughly ¾ of a word; 113k tokens is about a 250-page book. The test set was LongMemEval, a benchmark of questions about long chat histories."],
    sources: [{ label: "Context Rot (Chroma)", href: "https://www.trychroma.com/research/context-rot" }],
  },
  {
    id: "evidence-residue",
    chapter: "evidence",
    kind: "statement",
    transition: "rise",
    heading: "Residue: what's still in the chat but no longer true.",
    lines: [
      { text: "Old drafts, options you rejected, mistakes you corrected, side tangents." },
      { text: "The model rereads the whole chat every turn and can't tell which version is current.", more: "In one study (IFScale), models given hundreds of instructions at once followed the earliest ones best. An old rule can beat the correction you typed later." },
      { text: "New subtask? Start a new chat with a short note on where you are." },
      { text: "Let the AI draft that note, then fix it yourself. You know what's still true.", more: "A summary always leaves things out. The question is who decides what. When models summarise their own work they drop specifics (ACE study); your edit puts them back." },
    ],
    details: [
      "When not to restart: you're still on the same subtask and earlier wording matters, e.g. a paragraph you've refined line by line over many turns.",
      "Restarting loses whatever your note leaves out. In Chroma's test that loss was smaller than the confusion the full history caused.",
    ],
    sources: [{ label: "Context Rot (Chroma)", href: "https://www.trychroma.com/research/context-rot" }],
  },
  {
    id: "evidence-truncation",
    chapter: "evidence",
    kind: "statement",
    transition: "rise",
    heading: "Hitting the limit doesn't clean the chat.",
    lines: [
      { text: "When a chat outgrows the window, the app cuts the oldest turns or summarises them." },
      { text: "Cutting removes your first messages: often the task and its rules.", more: "Several guides report ChatGPT drops the oldest turns silently, with no warning in the reply. Apps differ and don't document it fully." },
      { text: "Old drafts in the middle survive, and the middle is where models look least.", more: "Lost in the Middle (Liu et al., 2023): models used information at the start and end of a long context best, and the middle worst." },
      { text: "Your own handoff note is the one cleanup you control." },
    ],
    sources: [
      { label: "Liu et al. — Lost in the Middle (TACL 2023)", href: "https://arxiv.org/abs/2307.03172" },
      { label: "What happens when ChatGPT's context window is full", href: "https://www.fileuploadgpt.com/blog/chatgpt-context-window-full" },
    ],
  },
  {
    id: "evidence-compaction",
    chapter: "evidence",
    kind: "stat",
    transition: "zoom",
    study: "Researchers gave AI agents standing rules (\"don't delete emails until I confirm\"), then let the agents' automatic summaries shrink their memory.",
    value: "17%",
    label: "of those rules survived the automatic summary, on average",
    meaning: "Most agents did worse than with no summarising at all. Restate rules that matter in a fresh chat.",
    source: "Lost in Compaction · Wang et al. 2026 · preprint",
    details: ["A rule-aware add-on kept over 90% of the rules, so the loss comes from how summaries are made, not from summarising as such. Preprint, not yet peer reviewed."],
    sources: [{ label: "Wang et al. — Lost in Compaction (2026)", href: "https://arxiv.org/abs/2608.11242" }],
  },
  {
    id: "evidence-ifscale",
    chapter: "evidence",
    kind: "stat",
    transition: "zoom",
    study: "Distyl gave 20 models between 10 and 500 instructions at once and checked how many were followed.",
    value: "68%",
    label: "of 500 instructions followed by the best model",
    meaning: "The rest were skipped without warning, mostly the later ones. A long rule list quietly loses rules.",
    source: "IFScale · Distyl 2025",
    sources: [{ label: "IFScale", href: "https://arxiv.org/pdf/2507.11538" }],
  },
  {
    id: "evidence-agentsmd",
    chapter: "evidence",
    kind: "stat",
    transition: "zoom",
    study: "ETH Zurich ran AI coding agents on real projects, with and without a standing instructions file (AGENTS.md).",
    value: "+20%",
    label: "cost when the file was included, with no reliable gain in success",
    meaning: "Files written by an AI were the only kind that made results worse.",
    source: "Evaluating AGENTS.md · ETH Zurich 2026",
    details: ["Instructions in the file were followed; overviews of the project were not useful. A later revision found the effect on success not statistically significant; the extra cost held."],
    sources: [{ label: "Evaluating AGENTS.md", href: "https://arxiv.org/abs/2602.11988" }],
  },
  {
    id: "evidence-deck",
    chapter: "evidence",
    kind: "widget",
    widget: "evidence-deck",
    guide: {
      name: "Seven studies on context size",
      shows: "Seven studies on what happens when an AI is given more text to read. Each card: who ran it, what they did, what they found.",
      try: "Filter by what each study argues. Open a card to read the setting and the finding.",
      point: "Most find more text hurts unless it's organised. The 'counterweight' cards show when extra detail does help.",
      data: ["study"],
    },
    transition: "push",
  },
  {
    id: "evidence-resolve",
    chapter: "evidence",
    kind: "statement",
    transition: "rise",
    heading: "Structure, not brevity.",
    lines: [
      { text: "A small, human-written always-on layer." },
      { text: "Detail lives in files loaded on demand." },
      { text: "Edit by small deltas — never a full rewrite.", more: "ACE: repeated LLM rewrites cause brevity bias and context collapse. Incremental, itemized updates win." },
    ],
    details: [
      "Less-is-more (Context Rot, IFScale, ETH, SkillReducer, Index Sickness) and brevity bias (ACE) are both true — at different layers.",
      "Caveat: Index Sickness is a single-case study where the author was also the evaluator, and the paper was written by an AI collaborator.",
    ],
  },

  // ── 03 memory ────────────────────────────────────────────────────────────
  { id: "memory", chapter: "memory", kind: "chapter", transition: "iris" },
  {
    id: "memory-tiers",
    chapter: "memory",
    kind: "widget",
    widget: "memory-tiers",
    guide: {
      name: "One file vs three tiers",
      shows: "One developer's rules file before and after the fix: one big file reread every message vs three files read at different times.",
      try: "Flip between 'bloated' and 'tiered'. The bar is how many lines the AI rereads on every single message.",
      point: "The fix wasn't fewer lines overall. It was moving history out of the file the AI rereads every time.",
      data: ["study"],
    },
    transition: "push",
  },
  {
    id: "memory-index-sickness",
    chapter: "memory",
    kind: "stat",
    transition: "zoom",
    study: "One developer built a project with an AI over 391 sessions, and logged every time they had to correct it.",
    value: "9 → 0",
    label: "corrections for the AI saying work was done when the files showed it wasn't",
    meaning: "9 of 45 corrections before history moved out of the rules file; 0 of 20 after. The AI stopped claiming work it hadn't done.",
    source: "Index Sickness · Zhang & Song 2026 · one project",
    details: [
      "Before: sessions 136–214 (57 logged). After: sessions 253–395 (38 logged). Corrections overall fell from 0.79 to 0.53 per session.",
      "Cutting the project's spec documents from ~1,100 to ~480 lines (−56%) came first and didn't help: the false 'done' claims clustered in the sessions right after.",
      "Single case: one project, and the developer who counted the corrections also wrote the paper. A detailed example, not proof.",
    ],
    sources: [{ label: "Zhang & Song — Index Sickness", href: "https://arxiv.org/abs/2606.19121" }],
  },
  {
    id: "memory-notebook",
    chapter: "memory",
    kind: "compare",
    transition: "wipe",
    heading: "Two notes instead of one.",
    columns: [
      { title: "Project card", lines: ["What's true now: goal, stage, decisions in force.", "5–15 lines. Goes into every chat."], emphasis: true },
      { title: "Archive", lines: ["What happened: old decisions, dropped ideas, why.", "Kept forever. Pasted only when needed."] },
    ],
    details: [
      "Example card: \"Paper: CHI'27, trust in AI tutors. Stage: drafting Results. Decided: effect sizes with CIs; Study 2 dropped. Don't rewrite my prose.\"",
      "Nothing is deleted. Old notes just stop riding along in every chat, where they compete with what's current.",
    ],
  },
  {
    id: "memory-delete",
    chapter: "memory",
    kind: "statement",
    transition: "rise",
    heading: "Delete. Don't annotate.",
    lines: [
      { text: "“Ignore the old approach” still sits in context." },
      { text: "Physical removal is the only reliable fix." },
    ],
    details: ["Index Sickness argues removal over annotation, which matches Chroma's distractor results."],
    sources: [{ label: "Zhang & Song — Index Sickness", href: "https://arxiv.org/abs/2606.19121" }],
  },
  {
    id: "memory-sycophancy",
    chapter: "memory",
    kind: "widget",
    widget: "sycophancy-bars",
    guide: {
      name: "Stored profiles and agreement",
      shows: "How much more often each model agreed with a user's opinion when it also had a stored profile of that user.",
      try: "Nothing to click. Each bar is one model; longer means it agreed more once it knew the user.",
      point: "Memory softens feedback, more in some models than others. For critique, use a chat with memory off.",
      data: ["study"],
    },
    transition: "push",
  },
  {
    id: "memory-critique",
    chapter: "memory",
    kind: "statement",
    transition: "rise",
    heading: "Critique runs get task context only.",
    lines: [
      { text: "An assistant that knows you grades you softer." },
      { text: "Carry the rubric in a skill — not your profile." },
    ],
    details: [
      "CHI 2026 replayed two weeks of real chats from 38 people. A short stored profile of the user (\"facts about me\") made models agree with the user's stated view more often than any other kind of context.",
      "WRITER's MIST benchmark points at how memory is made: pulling out short \"facts\" caused it. Keeping raw history instead roughly halved the effect; a written summary helped most.",
    ],
    sources: [
      { label: "Jain et al. (CHI 2026)", href: "https://dl.acm.org/doi/10.1145/3772318.3791915" },
      { label: "WRITER — MIST", href: "https://writer.com/engineering/personalized-context-degrades-ai-accuracy/" },
    ],
  },

  {
    id: "memory-yesman-run",
    chapter: "memory",
    kind: "compare",
    transition: "wipe",
    heading: "We ran the yes-man test: one claim, three chats",
    columns: [
      { title: "Temporary chat", lines: ["Memory off", "Score: 4/10", "Rewrite: “substantially reduces”"] },
      { title: "Normal chat", lines: ["Memory on", "Score: 5/10", "Rewrite: “substantially reduces”"] },
      { title: "Project chat", lines: ["Knows my work", "Score: 5/10", "Rewrite kept “eliminated”"], emphasis: true },
    ],
    details: [
      "The claim, planted with a flaw: “Splitting memory into two files eliminates false ‘task finished’ reports (Zhang & Song, 2026).” The flaw: that study is one developer's project, judged by the same person.",
      "Prompt, identical in each chat: rate it 1–10 for a lab audience, then list the three weaknesses a skeptical colleague would raise first. One run per chat, October 2026.",
    ],
  },
  {
    id: "memory-yesman-lesson",
    chapter: "memory",
    kind: "statement",
    transition: "rise",
    heading: "None of them checked the source.",
    lines: [
      { text: "All three attacked the word “eliminates”. Fair, but that fits any strong claim." },
      {
        text: "None found the real flaw: the study is one person's project.",
        more: "Each answer hedged with “if the paper supports it” instead of looking. The flaw was the sample size, not the verb.",
      },
      {
        text: "The chat that knew my work went easiest: its rewrite kept “eliminated”.",
        more: "One run per chat, so this is an anecdote that points the way the CHI 2026 study predicts. It is not evidence on its own.",
      },
      { text: "Habit: ask what the source actually measured. Don't wait for the AI to ask." },
    ],
  },

  // ── 04 skills ────────────────────────────────────────────────────────────
  { id: "skills", chapter: "skills", kind: "chapter", transition: "iris" },
  {
    id: "skills-levels",
    chapter: "skills",
    kind: "widget",
    widget: "skill-levels",
    guide: {
      name: "How a skill loads",
      shows: "The three parts of a saved skill, and when each one enters the AI's context during a chat.",
      try: "Step a task through the three stages and watch which parts get loaded.",
      point: "An unused skill costs about 100 tokens: just its description. So the description decides whether it ever fires.",
      data: ["illustration"],
    },
    transition: "push",
    details: ["Agent Skills became an open standard on 18 Dec 2025; Codex, Cursor, Copilot and others read the same SKILL.md format."],
    sources: [
      { label: "Agent Skills overview", href: "https://inference.sh/blog/skills/agent-skills-overview" },
      { label: "Skills best practices", href: "https://github.com/devskale/skale-skills/blob/main/docs/agent-skills-best-practices.md" },
    ],
  },
  {
    id: "skills-reducer",
    chapter: "skills",
    kind: "stat",
    transition: "zoom",
    study: "Researchers read 55,315 public AI skills: saved instruction files that tell an assistant how to do a task.",
    value: "60%+",
    label: "of a typical skill's text gave the model nothing it could act on",
    meaning: "Over a quarter never said when to use them. Cutting the filler made results slightly better (+2.8%).",
    source: "SkillReducer · 2026",
    sources: [{ label: "SkillReducer", href: "https://arxiv.org/abs/2603.29919" }],
  },
  {
    id: "skills-rubric",
    chapter: "skills",
    kind: "compare",
    transition: "wipe",
    heading: "Save your standards, not tricks.",
    columns: [
      { title: "Prompt trick", lines: ["\"You are a world-class editor. Be brutally honest.\"", "Tells the model how to act.", "Stops working when the model changes."] },
      { title: "Your standard", lines: ["\"One claim per paragraph. Each claim cited. Name disagreements; don't smooth them.\"", "Says what good work is in your field.", "Works with any model, and with a human RA."], emphasis: true },
    ],
    details: ["Test: would you give it to a new lab member unchanged? If yes, it's worth saving. Your advisor's feedback patterns and a venue's review criteria are good starting points."],
  },
  {
    id: "skills-wrong",
    chapter: "skills",
    kind: "list",
    transition: "fade",
    heading: "What goes wrong",
    numbered: true,
    lines: [
      { text: "Vague description — it never fires.", more: "26.4% of 55,315 public skills lack a routing description (SkillReducer)." },
      { text: "Padded body.", more: "Over 60% of the average body is non-actionable. Compressing descriptions 48% and bodies 39% improved quality 2.8%." },
      { text: "One giant skill.", more: "Prefer a short core plus reference files." },
      { text: "Self-rewriting skills.", more: "ACE's context-collapse finding predicts drift toward generic text unless edits are small and reviewed." },
    ],
    sources: [{ label: "SkillReducer", href: "https://arxiv.org/abs/2603.29919" }],
  },
  {
    id: "skills-split",
    chapter: "skills",
    kind: "compare",
    transition: "wipe",
    heading: "Three containers",
    columns: [
      { title: "Memory file", lines: ["What is true about this project."] },
      { title: "Skill", lines: ["How to do a recurring job."], emphasis: true },
      { title: "Script", lines: ["The deterministic part.", "Zero tokens re-deriving it."] },
    ],
  },

  // ── 05 connectors ────────────────────────────────────────────────────────
  { id: "connectors", chapter: "connectors", kind: "chapter", transition: "iris" },
  {
    id: "connectors-bill",
    chapter: "connectors",
    kind: "stat",
    transition: "zoom",
    study: "Anthropic measured what five connected tool servers (58 tools) add to every request before you type.",
    value: "~55k",
    label: "tokens of tool descriptions, sent with every message",
    meaning: "That's over a quarter of a 200k context window, spent before your question arrives.",
    source: "Anthropic testing",
    sources: [{ label: "Summary of Anthropic's post", href: "https://waleedk.medium.com/the-evolution-of-ai-tool-use-mcp-went-sideways-8ef4b1268126" }],
  },
  {
    id: "connectors-overhead",
    chapter: "connectors",
    kind: "widget",
    widget: "tool-overhead",
    guide: {
      name: "Tool descriptions you pay for",
      shows: "How much of a 200k context window tool descriptions use up before you type, for a given number of connected servers.",
      try: "Add or remove servers. Switch between loading everything, tool search, and code execution.",
      point: "Each connected server costs roughly 11k tokens on every message. Connect what this task needs, not everything.",
      data: ["estimate"],
    },
    transition: "push",
    details: [
      "Fixes, lightest first: fewer servers; on-demand tool search (~77k → ~8.7k); code execution against tools exposed as files (one task ~150k → ~2k).",
      "Code execution adds a sandbox you now have to secure.",
    ],
    sources: [{ label: "Code execution with MCP", href: "https://particula.tech/blog/code-execution-mcp-token-reduction-pattern" }],
  },
  {
    id: "connectors-trifecta-scope",
    chapter: "connectors",
    kind: "statement",
    transition: "rise",
    heading: "Leaks need an assistant that can act.",
    lines: [
      { text: "An ordinary chat can only answer you. That's not this risk." },
      { text: "The risk starts when it can act: send email, post, edit shared files." },
      { text: "Then anything it reads can carry hidden instructions.", more: "A web page, an email or a shared doc can contain text like \"send the attached file to…\". One real case: a public support ticket that made an Atlassian assistant leak private data." },
      { text: "Rule: an assistant that can act shouldn't read strangers' content in the same session." },
    ],
  },
  {
    id: "connectors-trifecta",
    chapter: "connectors",
    kind: "widget",
    widget: "trifecta",
    guide: {
      name: "The three-part leak",
      shows: "Three abilities an AI session can have. A hidden instruction can leak your data only when all three are on at once.",
      try: "Switch on what your assistant can do in one session and watch the triangle close.",
      point: "Turn off any one and the leak has no path. Easiest to drop: reading strangers' content while it can send things.",
      data: ["illustration"],
    },
    transition: "push",
    details: [
      "Private data + untrusted content + a way out = a session that can be prompt-injected into leaking.",
      "Real case: an Atlassian MCP server where a public support ticket could steal private data. MCP pushes the security decision onto the end user.",
    ],
    sources: [{ label: "Simon Willison — lethal trifecta", href: "https://simonwillison.net/2025/Aug/9/bay-area-ai/" }],
  },

  // ── 06 cost ──────────────────────────────────────────────────────────────
  { id: "cost", chapter: "cost", kind: "chapter", transition: "iris" },
  {
    id: "cost-prefix",
    chapter: "cost",
    kind: "statement",
    transition: "rise",
    heading: "The bill is the prefix.",
    lines: [
      { text: "Cache reads cost ~10% of input.", more: "Writes cost 1.25× (5-min) or 2× (1-hour): one reuse already breaks even." },
      { text: "Change anything early — everything after re-bills.", more: "Editing CLAUDE.md mid-session, reshuffling tools, switching models." },
      { text: "97% of one user's tokens were cache reads.", more: "74,493 logged turns. Anecdotal, but it shows where cost sits." },
    ],
    sources: [
      { label: "Prompt caching mechanics", href: "https://www.buildthisnow.com/blog/guide/development/claude-code-prompt-caching" },
      { label: "Reducing token usage", href: "https://app.stationx.net/articles/reduce-claude-code-token-usage" },
      { label: "Log analysis", href: "https://www.aakashx.com/blog/how-to-cut-claude-code-cost/" },
    ],
  },
  {
    id: "cost-calculator",
    chapter: "cost",
    kind: "widget",
    widget: "cache-calculator",
    guide: {
      name: "The cost of resending context",
      shows: "What it costs to resend the same opening text (instructions, memory, tool list) with every message, with and without caching.",
      try: "Change size, turns and price. Toggle 'edit memory mid-session' and watch one bar spike.",
      point: "Caching makes the repeated part about 10× cheaper. Editing memory mid-chat throws the cache away.",
      data: ["estimate"],
    },
    transition: "push",
  },
  {
    id: "cost-checklist",
    chapter: "cost",
    kind: "widget",
    widget: "guardrail-checklist",
    guide: {
      name: "Your habit checklist",
      shows: "The habits from these topics, as a checklist.",
      try: "Tick what's already true for you. Ticks are saved in this app.",
      point: "Count what you actually do, not what you agree with. An unticked item is your cheapest next step.",
      data: ["yours"],
    },
    transition: "push",
  },
  {
    id: "cost-hierarchy",
    chapter: "cost",
    kind: "compare",
    transition: "wipe",
    heading: "Fetch one level deeper, only when needed",
    columns: [
      { title: "Core file", lines: ["Names pointers."], emphasis: true },
      { title: "Reference files", lines: ["Hold the detail."] },
      { title: "Scripts", lines: ["Do the work."] },
    ],
  },

  // ── 07 local ─────────────────────────────────────────────────────────────
  { id: "local", chapter: "local", kind: "chapter", transition: "iris" },
  {
    id: "local-routing",
    chapter: "local",
    kind: "statement",
    transition: "rise",
    heading: "The case for local is data, not cost.",
    lines: [
      { text: "Research data may not be allowed to leave the machine." },
      { text: "Local for sensitive and bulk; cloud for hard reasoning." },
      { text: "16 GB → gpt-oss:20b · 24 GB → qwen3.6:27b", more: "From one 2026 guide. Verify on your actual machines before relying on it." },
    ],
    details: ['The "80% local" ratios quoted online are blog estimates, not measurements.'],
    sources: [
      { label: "Local vs cloud overview", href: "https://freeacademy.ai/blog/local-llms-vs-cloud-llms-ollama-privacy-comparison-2026" },
      { label: "Hardware guide", href: "https://aithinkerlab.com/best-local-llm-models-privacy-dev/" },
    ],
  },
  {
    id: "local-odysseus",
    chapter: "local",
    kind: "widget",
    widget: "odysseus-grid",
    guide: {
      name: "Odysseus, part by part",
      shows: "Each part of Odysseus, a free app for running AI models on your own computer, with our verdict on each.",
      try: "Read the tag on each card: supports this talk's argument, cuts against it, or neutral.",
      point: "Good for owning your data. Its automatic memory is the pattern the memory topic warns about.",
      data: ["opinion"],
    },
    transition: "push",
    details: [
      "Odysseus: released by Felix Kjellberg on 31 May 2026, MIT licensed.",
      "On 2 Oct 2026 he released Ajax, a 9B fine-tune of Qwen3.5 for agentic tool use inside Odysseus. Coverage is one day old — check before citing.",
    ],
    sources: [
      { label: "Odysseus repository", href: "https://github.com/pewdiepie-archdaemon/odysseus" },
      { label: "XDA hands-on", href: "https://www.xda-developers.com/tried-pewdiepie-open-source-ai-workspace-odysseus-weirdly-great/" },
      { label: "Ajax coverage", href: "https://tech-insider.org/pewdiepie-ajax-ai-model-openai-bans-2026/" },
    ],
  },
  {
    id: "local-verdict",
    chapter: "local",
    kind: "compare",
    transition: "wipe",
    heading: "Strong on ownership. Weak on restraint.",
    columns: [
      { title: "Shows ownership", lines: ["Compare: blind local vs cloud", "Cookbook: what your hardware runs"], emphasis: true },
      { title: "Shows the risks", lines: ["Brain: extracted, self-rewriting memory", "Agent: the agent quadrant"] },
    ],
  },

  // ── 08 human cost ────────────────────────────────────────────────────────
  { id: "human-cost", chapter: "human-cost", kind: "chapter", transition: "iris" },
  {
    id: "human-gap",
    chapter: "human-cost",
    kind: "widget",
    widget: "perception-gap",
    guide: {
      name: "Feeling vs stopwatch",
      shows: "A study timed 16 experienced developers with and without AI. Red: what the stopwatch said. Grey: what they felt. Blue: you.",
      try: "Set how much faster AI makes you feel. The red dot won't move: it's their measurement, not yours.",
      point: "Feeling faster isn't evidence of being faster. To get your own red dot, time yourself (link below).",
      data: ["study", "yours"],
    },
    transition: "push",
    details: [
      "METR RCT: 16 experienced open-source devs, 246 tasks, early-2025 tools. 19% slower with AI; they believed 20% faster. CI +2% to +39%.",
      "METR's 2026 follow-up changed design after 30–50% of invited developers declined to work without AI, which biases the sample.",
      "Anthropic RCT: 52 mostly junior devs learning an unfamiliar library. Debugging showed the largest gap.",
    ],
    sources: [
      { label: "METR RCT coverage", href: "https://scienceblog.com/t-a-randomized-trial-by-metr-found-that-experienced-developers-completed-real-coding-tasks-19-slower-when-allowed-to-use-ai-tools-yet-afterwards-they-estimated-on-average-that-ai-had-made-them-20-fast/" },
      { label: "Anthropic — AI assistance and coding skills", href: "https://www.anthropic.com/research/AI-assistance-coding-skills" },
    ],
  },
  {
    id: "human-learning",
    chapter: "human-cost",
    kind: "stat",
    transition: "zoom",
    study: "52 developers learned an unfamiliar Python library, half with an AI assistant, then took a quiz without AI.",
    value: "50% vs 67%",
    label: "average quiz score: learned with AI vs learned by hand",
    meaning: "Asking the AI to explain scored 65–86%. Letting it do the work scored under 40%.",
    source: "Anthropic RCT · 2026 · programming only",
    details: [
      "The study tested programming. Applying it to learning statistics or research methods is a reasonable guess, not a finding.",
      "Checking your understanding in a fresh chat combines this study with the sycophancy results; no study tested that combination.",
    ],
    sources: [{ label: "Anthropic — AI assistance and coding skills", href: "https://www.anthropic.com/research/AI-assistance-coding-skills" }],
  },
  {
    id: "human-quiz",
    chapter: "human-cost",
    kind: "widget",
    widget: "learning-quiz",
    guide: {
      name: "Quiz scores after learning",
      shows: "52 developers learned a new library, with or without AI, then took a quiz without AI. Bars: their average scores.",
      try: "Compare the striped bar (let the AI do it) with the last one (asked the AI to explain).",
      point: "How you use the AI mattered more than whether you used it. Asking for explanations kept learning intact.",
      data: ["study"],
    },
    transition: "push",
    sources: [{ label: "Anthropic — AI assistance and coding skills", href: "https://www.anthropic.com/research/AI-assistance-coding-skills" }],
  },
  {
    id: "human-framing",
    chapter: "human-cost",
    kind: "statement",
    transition: "rise",
    heading: "Measure. Don't trust the feeling.",
    lines: [
      { text: "Ask for explanations while learning." },
      { text: "Delegate once you know the terrain." },
      { text: "Critique over authorship." },
    ],
  },

  // ── 09 mistakes ──────────────────────────────────────────────────────────
  { id: "mistakes", chapter: "mistakes", kind: "chapter", transition: "iris" },
  {
    id: "mistakes-audit",
    chapter: "mistakes",
    kind: "widget",
    widget: "mistakes-audit",
    guide: {
      name: "Mistakes poll",
      shows: "Habits that seem sensible but backfire. Counts are anonymous answers from everyone using this copy of the site.",
      try: "Tick the ones you did this month. Tap a mistake to see why it backfires and what to do instead.",
      point: "If most of the room ticks the same one, that's the habit to fix first.",
      data: ["yours"],
    },
    transition: "push",
  },
  {
    id: "mistakes-exhibit",
    chapter: "mistakes",
    kind: "widget",
    widget: "spec-exhibit",
    guide: {
      name: "Two real vibe-coding specs",
      shows: "Two real prompts written to make AI site builders copy a web page, with a note on what goes wrong in each excerpt.",
      try: "Switch between the two specs and read the note under each excerpt.",
      point: "Long prompts mix instructions, made-up data and borrowed assets. Each one is a mistake from the catalog above.",
      data: ["illustration"],
    },
    transition: "push",
    details: [
      "Both specs were written to be pasted into an AI site generator and reproduce a page to the pixel.",
      "Together they show four catalog mistakes at once: instruction overload, invented data, borrowed assets, and directions mixed with content.",
    ],
  },

  // ── 10 tensions ──────────────────────────────────────────────────────────
  { id: "tensions", chapter: "tensions", kind: "chapter", transition: "iris" },
  {
    id: "tensions-evidence",
    chapter: "tensions",
    kind: "list",
    transition: "fade",
    heading: "Tensions in the evidence",
    lines: [
      { text: "Less-is-more vs brevity bias.", more: "Section 2 resolves it by layer. Convincing, or papering over a real disagreement?" },
      { text: "Coding evidence, research audience.", more: "Most rigorous studies are coding agents on repos; much research work is papers, tools and studies." },
      { text: "Curation costs time.", more: "When does curating memory cost more than re-explaining context?" },
      { text: "Personalization vs agency.", more: "The yes-man data suggests personalization can quietly undermine transparency. Sharpens the thesis, or complicates it?" },
    ],
  },

  // ── 11 build ─────────────────────────────────────────────────────────────
  { id: "build", chapter: "build", kind: "chapter", transition: "iris" },
  {
    id: "build-how",
    chapter: "build",
    kind: "statement",
    transition: "rise",
    heading: "Built by talking to an AI, under its own rules.",
    lines: [
      { text: "An AI coding assistant (Claude Code) wrote every line, in conversation." },
      { text: "The owner decided what to build, what was wrong, and what to cut." },
      {
        text: "The assistant rereads one short rules file each session. Everything else is looked up.",
        more: "That's the split from topic 03: a short card read every time, reference docs read on demand, and history kept in a separate log.",
      },
      { text: "Every decision goes in a log, so the next session doesn't argue it again." },
    ],
  },
  {
    id: "build-files",
    chapter: "build",
    kind: "widget",
    widget: "info-system",
    guide: {
      name: "The AI's files and the app's code",
      shows: "The files the AI reads while building this site, sorted by when it reads them, and how the app's code is layered.",
      try: "Switch between the AI's files and the app's code. Every count is read from the repository.",
      point: "It's topic 03 applied to a codebase: a short card read every time, docs looked up, history kept apart.",
      data: ["codebase"],
    },
    transition: "push",
  },
  {
    id: "build-log",
    chapter: "build",
    kind: "widget",
    widget: "decision-log",
    guide: {
      name: "Every decision, in order",
      shows: "Every decision logged while building this site, oldest first, with the owner's correction where there was one.",
      try: "Filter to the owner's corrections, or to the options that were tried and rejected.",
      point: "The AI's first drafts were often wrong in ways only the owner could see. The log stops the next chat repeating them.",
      data: ["codebase"],
    },
    transition: "push",
  },
  {
    id: "build-status",
    chapter: "build",
    kind: "list",
    transition: "fade",
    heading: "Four tools, no real users yet",
    lines: [
      {
        text: "Setup audit: checks a pasted rules file against patterns from the studies.",
        more: "The patterns are simple text matching. It has never been run on someone else's real setup, so expect false alarms.",
      },
      {
        text: "Self-assessment: 18 questions, a score per topic.",
        more: "We wrote the questions and chose the weights. Nobody has checked that the score means anything.",
      },
      {
        text: "Experiments: log A-vs-B runs of a habit on your own work.",
        more: "Templates come from the studies' claims. No experiment has been run in it yet.",
      },
      { text: "Knowledge base: your notes, filed by topic.", more: "Plain notes with a topic tag. It is empty until someone uses it." },
    ],
  },
  {
    id: "build-whim",
    chapter: "build",
    kind: "list",
    transition: "fade",
    heading: "Some of it was built on a whim",
    lines: [
      { text: "Glass lenses on the control board: built because the library could do it." },
      { text: "Six scroll-in styles for scenes: asked for variety, not needed for understanding." },
      { text: "The anonymous mistakes poll: means nothing until a room fills it in." },
      { text: "Preview images on sources: added for looks; they weigh 2.8 MB." },
    ],
    details: ["Kept for now because they cost little to run. Each would go first if the site had to shrink."],
  },
  { id: "end", chapter: "end", kind: "end", transition: "fade" },
];
