"""initial schema

Revision ID: 6c41f8f22ad0
Revises:
Create Date: 2026-10-03 20:12:53.426549
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "6c41f8f22ad0"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_responses",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("mistakes", postgresql.ARRAY(sa.String(length=64)), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_responses")),
    )
    op.create_table(
        "board_pins",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("label", sa.String(length=48), nullable=False),
        sa.Column("control", sa.Float(), nullable=False),
        sa.Column("memory", sa.Float(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("control BETWEEN 0 AND 1", name=op.f("ck_board_pins_control_unit")),
        sa.CheckConstraint("memory BETWEEN 0 AND 1", name=op.f("ck_board_pins_memory_unit")),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_board_pins")),
    )
    op.create_table(
        "checklist_items",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("done", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_checklist_items")),
    )
    op.create_table(
        "notes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("section", sa.String(length=64), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notes")),
    )
    op.create_index(op.f("ix_notes_section"), "notes", ["section"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_notes_section"), table_name="notes")
    op.drop_table("notes")
    op.drop_table("checklist_items")
    op.drop_table("board_pins")
    op.drop_table("audit_responses")
    # ### end Alembic commands ###
